### ISSUE TITLE
Not working with primevue and tailwind project

### ISSUE THREAD

**Issue by mbaljeetsingh** [modbender/nuxt-disqus#5]
I have added `nuxt-disqus` and followed the instruction from the docs.
```
<ClientOnly>
    <DisqusComments :identifier="`/blog/${route.params.id}`" :title="article.title" :url="article._path" />
  </ClientOnly>
```

Output:
![image](https://github.com/user-attachments/assets/9de244f3-4c54-4073-a0dd-e95ebf153c3a)

I'm getting following error in the console and the disqus comments don't show up.

![image](https://github.com/user-attachments/assets/de2aefac-3458-4e55-ac42-9db4ec54b52e)

And following is when i click on embed.js error
![image](https://github.com/user-attachments/assets/e3c8b351-9075-4a0d-a181-a798d9119a8e)

Thanks

**Comment by modbender** [comment]
That embed.js comes straight from Disqus universal code so can't really say it's this package's problem:
https://help.disqus.com/en/articles/1717112-universal-embed-code

If I had to still guess I think you should look at the `body` or `html` element color for having wrong value.
